# fly.toml app configuration file generated for backprojectlifelinkai on 2025-04-22T16:00:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backprojectlifelinkai'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  # This is redundant with the memory value above, so I've removed it
  # memory_mb = 1024

# Added volume mount configuration for storing the model file
[mounts]
  source = "model_data"
  destination = "/app/model_data"