app = "backprojectlifelinkai"
primary_region = "cdg"

[build]
  # S'assurer que le contexte de build est correct
  dockerfile = "Dockerfile"
  
[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "get"
    path = "/"
    timeout = "5s"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1