app = 'backprojectlifelinkai'
primary_region = 'cdg'

[build]

[[mounts]]
  source = 'model_data'
  destination = '/app/model_data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
